-- Up Migration
CREATE UNIQUE INDEX IF NOT EXISTS UNIQUE_ACTIVE_AUCTION_PER_SHOP ON auctions (shop_id) WHERE (status = 'ACTIVE');

-- Down Migration
DROP INDEX IF EXISTS UNIQUE_ACTIVE_AUCTION_PER_SHOP;
